### ISSUE TITLE
Run tests on Travis

### ISSUE THREAD

**Issue by roman01la** [roman01la/JSONFormData#10]
The project is on Travis: https://travis-ci.org/roman01la/JSONFormData, but it doesn't really runs tests.

**Comment by EmarJ** [comment]
Maybe something like phantomjs?

**Comment by roman01la** [comment]
@EmarJ yes, or even [jsdom](https://github.com/tmpvar/jsdom)

**Comment by EmarJ** [comment]
@roman01la I quickly tried to use phantomjs (since its [already present](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS) in Travis) with [this](https://github.com/ariya/phantomjs/blob/master/examples/run-jasmine.js) test runner but I get an error. Apparently that js file has to be updated with the current jasmine test html markup

If you want to try that route I can work a bit on it later.

**Comment by roman01la** [comment]
@EmarJ Sure, thank you. I don't really care how the tests are going to be executed, I just want them to be actually used on CI server.

**Comment by EmarJ** [comment]
Added test runner to use with phantomjs. Since we are touching tests I'm going forward to update Jasmine to latest version and see if the runner is still fine

**Comment by roman01la** [comment]
Merged, thanks!
